### PR TITLE
WIP - initial commit for average_windows

### LINKED ISSUE #62: Implement a way to define average windows waveform PVs
Under the `LLRF HLS` screen, there are 6 windows waveforms PVs:
- Average Window 0 to 2
- Complex window 0 to 2

These windows are waveform PVs. We need to add a tool here to let the user generate these PVs from some parameters. For example, for a rectangular window, the user need to define the `start` and `stop` time, and from these 2 parameters the waveform PV data should be automatically generated and  `caput`ed to the corresponding PV.

We should also support some other standard windows functions, like some of [theses](https://en.wikipedia.org/wiki/Window_function#A_list_of_window_functions). We should decide which ones to support, and which parameters to use to generated them.

### PR DESCRIPTION
**Pull request by cristinasewell**
Will eventually close #62

### CODE REVIEW

**Comment by cristinasewell** [comment]
@jesusvasquez333 do you think I should keep the `Plot` button here? this one plots the actual PV - to the same plot (after it clears it from the Drawing)

Also, do you think i am missing anything related to validation? Should I give users a min value for window at all? for now it is validating with `QIntValidator` for ends and starts - so it will allow the user to have the smallest int possible i think. 

The warning that I have there is not too pretty, because if the user only wants to draw the I Window, and not the Q window - he/she will be allowed to draw it, but still get a warning - what do you think about this?

And one more thing, if I plot the curve - I should be getting the same plot back correct?

**Comment by jesusvasquez333** [comment]
I don't think it is necessary to have the plot button. And I don't like it clear the plot. 

We should validate that stop > start.

Yes, the error message are not pretty. Maybe you can just show errors if neither I and Q are defined (I.e. only defining I or Q is valid)?

**Comment by cristinasewell** [comment]
@jesusvasquez333  i have fixed those things mentioned above, please let me know what you think now when you get a chance.
Also, do you think we can merge this if it is good enough as a first release and then we can add the other window types later to it - maybe people will give us some feedback in the meantime

**Comment by cristinasewell** [comment]
@jesusvasquez333  i added the option to add ZEROS in, please check that when you get a chance. 
I also color coded the two buttons - let me know if this is a bit too much :) we can take that off

**Review by jesusvasquez333 — APPROVED** [review]

**Pull request merged**
