### PR TITLE
ENH: add demod reference channel menus 

### LINKED ISSUE #85: Add menu combo boxes for the Demod Reference Channels

### PR DESCRIPTION
**Pull request by cristinasewell**
Will eventually close #85

### CODE REVIEW

**Comment by cristinasewell** [comment]
@jesusvasquez333  i would like you to give me some feedback on this when you get a chance, is this what you meant?
I only added the menues for the PLL screen for now, just to see how it would work - please let me know what you think. 

Also, please note that for the CLK reference, if people selected `10` you won't see anything in the menu - we don't have a ch 10 correct?

Also, do you thing I should be adding the ADC0, ADC1.. and so on??  - this can get a bit confusing because we have Mux1 and Mux0 and they have the same names (ADC0, ADC1...) - so i would have to mention the muxes too in the label to make it clear?

**Comment by cristinasewell** [comment]
@jesusvasquez333  I added the menus for the rf_dac_out as well - i did not test them to see if they actually send the values - will i mess up with their testing system if I test this?

**Comment by cristinasewell** [comment]
@jesusvasquez333 i added the missing Demod Channels, also i corrected the labels, I had it switched: instead of `DwnCnv: ` I had `UpCnv` and vice-versa. 
Can you please test it again? - thanks a lot

**Review by jesusvasquez333 — APPROVED** [review]
Works great!

**Comment by cristinasewell** [comment]
ok perfect, i'll merge that in

**Comment by jesusvasquez333** [comment]
I setup a `camonitor` on the PVs, and select all the menu option and make sure the right values was written to the PV. For example, for the `CLK` signal I saw:
```bash
[jvasquez@rhel6-64j ~]$ camonitor SIOC:B084:RF52:0:CLOCK_REFSELECT
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-03 18:33:35.802041 10
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:15.909973 0
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:18.569883 1
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:20.552547 2
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:21.980244 3
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:23.411886 4
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:25.266210 5
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:26.923467 6
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:28.682754 7
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:30.280992 8
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:31.795133 9
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:33.356781 10
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:35.043988 11
SIOC:B084:RF52:0:CLOCK_REFSELECT 2020-08-05 09:47:37.238811 10
```

when selecting all the menu options in sequential order.

**Pull request merged**
